apiVersion: v1
kind: ServiceAccount
metadata:
  name: escalator
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: escalator
  labels:
    k8s-addon: escalator.addons.k8s.io
    k8s-app: escalator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - update
  - patch
  - watch
  - list
  - get
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - escalator-leader-elect
  resources:
  - leases
  verbs:
  - get
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: escalator
  labels:
    k8s-addon: escalator.addons.k8s.io
    k8s-app: escalator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: escalator
subjects:
  - kind: ServiceAccount
    name: escalator
    namespace: kube-system
